### ISSUE TITLE
Need permission to save translations

### ISSUE THREAD

**Issue by scootergrisen** [getsolus/budgie-translations#6]
I want to translate on https://translate.getsol.us/ but if i hover the Save button it says i don't have the permission to do so.

**Comment by kmarud** [comment]
I have the same situation, I can only add a suggestion :/ 
I would prefer to add my translations by Pull Request, why is it not allowed?
Regards

**Comment by JoshStrobl** [comment]
> I want to translate on https://translate.getsol.us/ but if i hover the Save button it says i don't have the permission to do so.

This is correct. The correct process involves an individual for the respective language team reviewing and approving the translations.

>  I would prefer to add my translations by Pull Request, why is it not allowed?

Because I do not speak every language in the world, however we have many folks part of various translator teams which speak that respective language and thus are best equipped to review it and communicate any questions related to translation and the meaning of various aspects of the original terminology.

The correct process is to provide details via [our forum](https://discuss.getsol.us/d/5774-call-to-action-translators-needed) on what certain languages are not seeing reviews. If there is no translator team for it, I may end up creating one and assigning you to it. Otherwise, you will need to exercise patience.

**Comment by scootergrisen** [comment]
I don't see any way on knowing about any danish language team that might exist.
